### ISSUE TITLE
CARELESSNESS

### ISSUE THREAD

**Issue by mason2smart** [discobots2587/2016-Stronghold#7]
If there is a move command, it usually goes in execute

If you are editing a CANTalon branch, code CANTalons not Talons

If you are setting speeds with a command, you **MUST** set the speeds to zero in the end() method!

**Comment by tmcdo1** [comment]
Mason, Don't mess with it. Some of the move commands have it in initialize because they are  used by holding a button down. They might not have set the motors to zero in the end because for the motors to work they need to be constantly given a value, so if a command isn't constantly running the motor isn't getting a value so it stops. Also, not all those motors were running through CAN but they were on the CAN electrical board.Before you assume it's a careless mistake, ask someone else.




Sent from my T-Mobile 4G LTE Device

-------- Original message --------

**Comment by mason2smart** [comment]
All the motors are can now...  The code did not work A couple examples of issues I encountered-- Some commands did not end when they were supposed to. Tried and tested on the robot and it didn't work. Drivetrain subsystem - the motors were added in the wrong order and messed up the drive controls and caused them to fight each other during turning. Axis 3 is the right trigger not the right joystick on the controller...

  It's ok, that's why we are working together - we are a team after all. Please try to ignore my rudeness as I have had a very long day and almost ended up in the hospital as Curtis almost ran me over with the robot and totaled my brand new laptop. :1: (

My laptop now runs approx 20 Celsius hotter and now hits over 90 Celsius and the entire bezel is warped and the hinge is broken

Thanks,
Mason
